plugins {
    id 'java'
    id("io.freefair.lombok") version "8.2.1"
}

group = 'ru.netology'
version = '1.0-SNAPSHOT'
java{
    sourceCompatibility = 11
}
compileJava.options.encoding = "UTF-8"
compileTestJava.options.encoding = "UTF-8"

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    implementation'org.junit.jupiter:junit-jupiter:5.10.2'
    runtimeOnly'org.junit.jupiter:junit-jupiter:5.10.2'
}

test {
    useJUnitPlatform()
}